curl http://themes.tehnoremont-ds.com/atina/css/buttons/buttons.css > css/buttons/buttons.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/antiscroll.css > css/plugins/antiscroll.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/ui/jquery-ui.css > css/plugins/ui/jquery-ui.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.fancybox.css > css/plugins/jquery.fancybox.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.mCustomScrollbar.css > css/plugins/jquery.mCustomScrollbar.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/fullcalendar.css > css/plugins/fullcalendar.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/chosen.css > css/plugins/chosen.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/tipsy.css > plugins/tipsy.css 
curl http://themes.tehnoremont-ds.com/atina/css/plugins/xbreadcrumbs.css > plugins/xbreadcrumbs.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.easy-pie-chart.css > css/plugins/jquery.easy-pie-chart.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.dataTables.css > css/plugins/jquery.dataTables.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jplayer.css > css/plugins/jplayer.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/ui.daterangepicker.css > css/plugins/ui.daterangepicker.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.ibutton.css > css/plugins/jquery.ibutton.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.plupload.queue.css > css/plugins/jquery.plupload.queue.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jquery.cleditor.css > css/plugins/jquery.cleditor.css
curl http://themes.tehnoremont-ds.com/atina/css/plugins/jqueryFileTree.css > css/plugins/jqueryFileTree.css
